spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
    
datasource:
  url: jdbc:mysql://127.0.0.1:3306/platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  slave-list:
    name: slave
    url: jdbc:mysql://127.0.0.1:3306/platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin#123
