spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: false
    
datasource:
  master:
      initialize: true
      jdbc-url: "jdbc:mysql://127.0.0.1:3306/replication?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      username: "root"
      password: "1234"
  slave:
      initialize: true
      jdbc-url: "jdbc:mysql://127.0.0.1:3307/replication?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      username: "root"
      password: "1234"
