spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: false
    
datasource:
  master:
      initialize: true
      jdbc-url: "jdbc:mysql://127.0.0.1:3306/platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      username: "root"
      password: "admin#123"
      initial-size: 10
      max-active: 10
      max-idle: 20
      min-idle: 10
      max-wait: 6000
      default-auto-commit: true
      max-total: 20
      validation-query: select 1
      pool-prepared-statements: true
  slave:
      initialize: true
      jdbc-url: "jdbc:mysql://127.0.0.1:3306/platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      username: "root"
      password: "admin#123"
      initial-size: 10
      max-active: 10
      max-idle: 20
      min-idle: 10
      max-wait: 6000
      default-auto-commit: true
      max-total: 20
      validation-query: select 1
      pool-prepared-statements: true
